server:
  port: 8080

#mysql 链接配置
spring:
    datasource:
        name: spider
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.cj.jdbc.Driver
          #基本属性
          url: jdbc:mysql://127.0.0.1:3306/spider?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
          username: root
          password: root
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    rabbitmq:
        host: 10.231.20.61
        port: 5672
        username: 000001
        password: 000001
        publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调


    swagger: #swagger
      enable: true #开启swagger
      base-package: com.sy.spider
      title: spider
      description: spider tool
      version: 1.0
      contact: #联系人信息
        name: peter
        email: 6347727@qq.com
      security: #（开启后访问 swagger-ui.html 会自动路由到登陆页面，保障接口信息不被暴露）
        filter-plugin: true
        username: admin
        password: admin

    redis: #redis
      database: 0 #redis数据库索引，默认为0
      host: localhost #服务地址
      port: 6379 #端口
      password: #密码，默认为空，本地没有设置密码，所以这里不填写
      jedis:
        pool:
          max-active: 8 #连接池最大的连接数，若使用负值表示没有限制
          max-wait: -1 #连接池最大阻塞等待时间，若使用负值表示没有限制
          max-idle: 8 #连接池中的最大空闲连接
          min-idle: 0 #连接池中的最小空闲连接
      timeout: 5000 #连接超时时间（单位为毫秒）

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.sy.spider.model  # 注意：对应实体类的路径



#pagehelper 分页工具
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

#logback配置文件（重命名logback.xml 必须配置）
logging:
  config: classpath:logback-spring.xml #自定义单个log文件大小，默认50MB
  path: D:/data/log

#业务配置
dzh:
  execute:
    thread: 10
    pipiline: filePipeline #定义需要的处理通道
  process:
    breakPoint: 0
    pageSize: 1000 #一次查询多少页
  pipeline:
    file:
      savePath: D:\\data\\pic #人像图上保存目录
  simulate:
    photoPath: D:\\data\\trdk\\pic1\\T_PHOTO_20171205_171532_0 #模拟图片源目录